# Generated by Django 4.2.7 on 2023-12-14 21:33

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bizmarrow_learning_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStaffs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizmarrow_learning_app.staffs')),
            ],
        ),
        migrations.CreateModel(
            name='LearnerVideo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('video_url', embed_video.fields.EmbedVideoField()),
                ('title', models.CharField(max_length=10000)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizmarrow_learning_app.students')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizmarrow_learning_app.staffs')),
            ],
        ),
    ]
