# Generated by Django 4.2.7 on 2023-12-15 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizmarrow_learning_app', '0002_videostaffs_learnervideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videostaffs',
            old_name='video_url',
            new_name='message',
        ),
    ]
