# Generated by Django 4.2.7 on 2023-12-16 21:16

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bizmarrow_learning_app', '0004_remove_videostaffs_title_videostaffs_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoStudents',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', embed_video.fields.EmbedVideoField(null=True)),
                ('message', models.CharField(max_length=250, null=True)),
                ('description', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizmarrow_learning_app.staffs')),
            ],
        ),
        migrations.DeleteModel(
            name='LearnerVideo',
        ),
    ]
