# Generated by Django 4.2.7 on 2023-12-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bizmarrow_learning_app', '0005_videostudents_delete_learnervideo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videostudents',
            old_name='staff_id',
            new_name='student_id',
        ),
    ]
