# Generated by Django 4.2.7 on 2023-12-16 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bizmarrow_learning_app', '0006_rename_staff_id_videostudents_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videostudents',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bizmarrow_learning_app.students'),
        ),
    ]
