# Generated by Django 4.2.7 on 2023-12-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizmarrow_learning_app', '0008_videostudents_thumbnail_alter_videostudents_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='videostaffs',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='media/thumbnail'),
        ),
    ]
